--- 
services: 
  mysql-server: 
    image: "mysql:8.0"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes: 
      - "mysql-data:/var/lib/mysql"
    networks:
      - mynet
    restart: always
  phpmyadmin: 
    image: "phpmyadmin/phpmyadmin:latest"
    environment:
      PMA_HOST: mysql-server 
      UPLOAD_LIMIT: 1G
      PMA_PORT: 3306
    networks:
      - mynet
    depends_on:
      - mysql-server
    ports: 
      - "5000:80"
    restart: always
  web-server: 
    build: 
      args:
        user: ahmad
        uid: 1000
      context: "."
      dockerfile: php.Dockerfile
    depends_on:
      - mysql-server
    ports: 
      - "8080:80"
    restart: always
    volumes: 
      - "./html/:/var/www/html/"
    networks:
      - mynet
version: "3.3"
volumes: 
  mysql-data:
networks:
  mynet:
